using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TN.Shared.Domain.Primitive;

namespace TN.Shared.Domain.Entities.AuditLogs
{
    public class AuditLog : AutoGeneratedEntity
    {
        public AuditLog(
            ) : base()
        {

        }

        public AuditLog(
            string? userId,
            string? tableName,
            string? primaryKey,
            string? fieldName,
            string? typeOfChange,
            string? oldValue,
            string? newValue,
            string? hashValue,
            string? schoolId,
            DateTime createdDate
            ) : base()
        {
            UserId = userId;
            TableName = tableName;
            PrimaryKey = primaryKey;
            FieldName = fieldName;
            TypeOfChange = typeOfChange;
            OldValue = oldValue;
            NewValue = newValue;
            HashValue = hashValue;
            SchoolId = schoolId;
            CreatedDate = createdDate;

        }

        public string? UserId { get; set; }
        public string? TableName { get; set; }
        public string? PrimaryKey { get; set; }
        public string? FieldName { get; set; }
        public string? TypeOfChange { get; set; }
        public string? OldValue { get; set; }
        public string? NewValue { get; set; }
        public string? HashValue { get; set; }
        public string? SchoolId { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}
