name: cicd-test

on:
  push:
    branches:
      - stagging

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Display Current Directory
        run: ls -la

      - name: Publish .NET Project
        working-directory: ./SchoolApp
        run: |
          dotnet restore
          dotnet publish -c Release -o ./app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./SchoolApp
          file: ./SchoolApp/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/SchoolApp:latest
            ${{ secrets.DOCKER_USERNAME }}/SchoolApp:${{ github.run_number }}

      - name: Verify Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/SchoolApp:latest

      - name: (Optional) Run Docker Container
        run: |
          docker stop SchoolApp-container || true
          docker rm SchoolApp-container || true
          docker run -d --name SchoolApp-container -p 8089:80 ${{ secrets.DOCKER_USERNAME }}/SchoolApp:latest
          docker ps
